### ISSUE TITLE
Submenu formatting inconsistent with Folder Notes plugin

### ISSUE THREAD

**Issue by bonwag** [aaaaalexis/obsidian-cupertino#11]
There is a style conflict with the Folder Notes plugin - sub-menus are not styled with the same vertical padding as the parents, so lower level navigation appears more spaced out. Not sure if this is a theme or a plug-in solution - but it is not happening in other themes like Blue Topaz with the same settings.

**Comment by aaaaalexis** [comment]
Fixed in 1.1.2 https://github.com/aaaaalexis/obsidian-cupertino/commit/7c8527ce8d6c7e49d989266f7c054c41966ae6b7

**Comment by bonwag** [comment]
Much better; thank you @aaaaalexis
