### ISSUE TITLE
Advanced tables - padding around left-aligned labels

### ISSUE THREAD

**Issue by macintacos** [aaaaalexis/obsidian-cupertino#12]
Using this plugin: https://github.com/tgrosinger/advanced-tables-obsidian

UI looks like this with this theme:

![CleanShot 2024-12-30 at 17 09 03@2x](https://github.com/user-attachments/assets/2feea9c8-71c6-4d04-bea7-d0f6569b6665)

Any chance the padding could be a little better? Specifically, on the lefthand side, the labels for the buttons are all a little squished against the left side of its bounding box.

**Comment by aaaaalexis** [comment]
Fixed in 1.1.3 https://github.com/aaaaalexis/obsidian-cupertino/commit/af2fb47be072a5eaa7a7def7386cc5e74fbe7a38
