### ISSUE TITLE
Line separator is barely visible in dark mode. 

### ISSUE THREAD

**Issue by prwnr** [aaaaalexis/obsidian-cupertino#13]
Hey! 

Would it be possible to make the line separator `---` a bit more visible in dark mode? it's hard to spot with lower brightness, so especially in a dark room when phone lowers it to 5-10% 

See my screenshot, it contains the separator but it's really hard to notice on phone if you will lower the brightness - at least on iPhone 13 Pro, as the newer models have more nits from what I know and it could be better there. 

![image](https://github.com/user-attachments/assets/e916e239-39fc-44c9-9b5e-555ae6f33403)

Great work with the theme!

**Comment by aaaaalexis** [comment]
Fixed in 1.1.3 https://github.com/aaaaalexis/obsidian-cupertino/commit/bfd58ad07987fdd5009b6ea768ba80d55746673e
