### ISSUE TITLE
Buttons style doesn't match the native MacOS style

### ISSUE THREAD

**Issue by tmsbn** [aaaaalexis/obsidian-cupertino#15]
The buttons in the settings and other Obsidian pages for the theme look a little different than standard macOS buttons.  I've attached a picture showing the Obsidian buttons compared to a native macOS button for reference.

<img width="824" alt="Screenshot 2024-12-31 at 5 45 40 AM" src="https://github.com/user-attachments/assets/d9592240-64e3-4034-8e3b-ddc4a9c20a03" />

![image](https://github.com/user-attachments/assets/3b6b3952-d320-467a-9b2a-bac589ea2f8a)

Perhaps it needs to be tad flatter with a lesser gradient?

**Comment by aaaaalexis** [comment]
Good eyes! [I have made changes](https://github.com/aaaaalexis/obsidian-cupertino/commit/ed3192920164eef313d22d77f809e2788d96e731) to the modal button that will be available next build. For settings page, I'm trying to match System Settings.app. Still looks a bit off but not high priority now.

On a side note, default accent on macOS is `#007AFF`.

**Comment by tmsbn** [comment]
Excellent! Thank you for the quick response. I am curious how often do you release builds?

**Comment by aaaaalexis** [comment]
Likely daily. Just random really
