### ISSUE TITLE
Smoother animations on mobile?

### ISSUE THREAD

**Issue by PurposeRefined1179** [aaaaalexis/obsidian-cupertino#16]
I don't know if you can see it in the video, but obsidian animations on iOS and iPadOS feel a little abrupt at the end (maybe it's just me idk). 

https://github.com/user-attachments/assets/f8948668-7bc0-469e-8d5a-b61422d6ef1b

https://github.com/user-attachments/assets/d079e255-2b1c-4efc-875f-5b04fed8fb72

I also think there should be a file switcher button at the top like the "Browse" button in iOS files app. A new user will find the current layout unintuitive at first: how would they know that swiping left or right opens those menus?

**Comment by aaaaalexis** [comment]
1. Unfortunately animations on mobile are set dynamically by Obsidian with no ways to override. 
2. New user are likely to try Obsidian before installing theme. Even when Cupertino is installed, when the opened file is in root folder (where new users are likely to start, I assume), the sidebar button would still show.
