### ISSUE TITLE
Suggestion (for Dataview queries)

### ISSUE THREAD

**Issue by CosmicCatAndBibbity** [aaaaalexis/obsidian-cupertino#2]
![image](https://github.com/user-attachments/assets/8bab2aba-e12a-42c5-9e71-cab6f1c87aed)

Probably make this table have rounded edges or with a background, like the properties?

![image](https://github.com/user-attachments/assets/387abb51-89c6-40c6-bed7-3f5860e12d4b)

**Comment by aaaaalexis** [comment]
Added in 1.1.0 https://github.com/aaaaalexis/obsidian-cupertino/commit/ac76c138159308c471c2c7548c97a3c67ecc7d2a
