### ISSUE TITLE
Pinned commands overlaying keyboard and search bar

### ISSUE THREAD

**Issue by bangsluke** [aaaaalexis/obsidian-cupertino#3]
![image](https://github.com/user-attachments/assets/447e19a6-6e3b-4694-adc8-cd7a729dba99)

**Comment by aaaaalexis** [comment]
Fixed in 1.1.1 https://github.com/aaaaalexis/obsidian-cupertino/commit/f13c091457e9b20bdc29746b83103a7fea6dcce8
