### ISSUE TITLE
Tabs overflow to the right past menu buttons

### ISSUE THREAD

**Issue by InterstellarOne** [aaaaalexis/obsidian-cupertino#9]
![image](https://github.com/user-attachments/assets/da710d52-1436-4ef3-95e5-3ff555b929f8)

Using Obsidian in Fedora Linux.

**Comment by javiavid** [comment]
+1 
windows 11

**Comment by aaaaalexis** [comment]
Fixed in 1.1.2 https://github.com/aaaaalexis/obsidian-cupertino/commit/719a835d54f22c6f8291db5f62021c6bf0fb847c

**Comment by d-eniz** [comment]
@aaaaalexis This still seems to be an issue in version 1.7.2.

![Image](https://github.com/user-attachments/assets/56ba577c-e609-4ef6-a5e1-0713a8099eda)
![Image](https://github.com/user-attachments/assets/0b2cfcea-13af-4659-ac0a-c999952a4ef2)
![Image](https://github.com/user-attachments/assets/76fa940c-8845-410d-9f43-0b8bafbf5c11)

I am using Obsidian 1.8.10 on a Windows 10 system.
